include:
  - ./compose-popp-server.yaml
  - ./compose-vsdm-server.yaml

services:
  card-terminal-client:
    image: de.gematik.ti20.simsvc.client/card-terminal-client-simservice:local
    ports:
      - "8000:80"
      - "5005:5005"
    environment:
      - OTEL_SERVICE_NAME=card-terminal-client
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - otel-collector

  vsdm-client:
    image: de.gematik.ti20.simsvc.client/vsdm-client-simservice:local
    ports:
      - "8220:80"
      - "5006:5006"
    environment:
      - POPP_HTTP_URL=http://popp-zeta-pep:80
      - POPP_WS_URL=ws://popp-zeta-pep:80
      - VSDM_RESOURCE_SERVER_URL=http://vsdm-zeta-pep:80
      - VSDM_PDP_URL=http://vsdm-zeta-pdp:80/auth/realms/zeta-guard
      - OTEL_SERVICE_NAME=vsdm-client
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "7100:7100"
    command:
      - '--config.file=/etc/prometheus/config.yaml'
      - '--web.listen-address=:7100'

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_PASSWORD_MUST_CHANGE=false
    ports:
      - "7001:3000"
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data:

networks:
  default:
    name: vsdm_network

