server:
  port: 8220

otel:
  sdk:
    disabled: true

popp:
  http:
    url: http://localhost:9110
  ws:
    url: ws://localhost:9110

vsdm:
  resourceServerUrl: http://localhost:9120
  pdpUrl: http://localhost:9122
