app.version: 0.0.1-dev

server:
  error:
    whitelabel.enabled: false
    include-message: always
  port: ${SERVER_PORT:80}

popp:
  http:
    url: ${POPP_HTTP_URL}
  ws:
    url: ${POPP_WS_URL:}

vsdm:
  resourceServerUrl: ${VSDM_RESOURCE_SERVER_URL}
  pdpUrl: ${VSDM_PDP_URL}
