server:
  port: ${SERVER_PORT:80}

proxy:
  http:
    url: ${PROXY_HTTP_URL:http://popp-server}
  ws:
    url: ${PROXY_WS_URL:ws://popp-server}
  sec:
    store:
      path: "./zetakeystore.p12"
      pass: testpassword
    key:
      alias: zetamock
      pass: testpassword

otel:
  sdk:
    disabled: true

well-known:
  issuer: ${WK_ISSUER:http://zeta-pep-popp}
  auth_ep: ${WK_AUTH_EP:http://zeta-pdp-popp/auth}
  token_ep: ${WK_TOKEN_EP:http://zeta-pdp-popp/token}
  nonce_ep: ${WK_NONCE_EP:http://zeta-pdp-popp/nonce}
